export default {
	GANStart: 'GANStart',
	PIN: 'PINScreen',
	ForgetPassword: 'ForgetPassword',
	OTP: 'OTPScreen',
	NewPassword: '	NewPasswordScreen',
	Loading: 'LoadingScreen',
	Home: "HomeScreen",
	ABAScreen : "ABAScreen",
	ReportsScreen: "ReportsScreen",
	Mortgagetype: "Mortgagetype",
	Capitalowner: "Capitalowner",
	SettingScreen: "SettingScreen",
	Inverstors:"Investors",
	Mortgage: "Mortgage",
	Additionalcapital : "Additional capital",
	Generalexpenses: 'Generalexpenses',
	Generalexpenses2: 'Generalexpenses2',
	Buildmoney: 'Buildmoney',
	Raisemoney: 'Raisemoney',
	Actualcollection: 'Actualcollection',
	Prepaidinterest: 'Prepaidinterest',
	Totalinterest: 'Totalinterest',
	Totalprincipal: 'Totalprincipal',
	TodayLoan_amount: 'TodayLoan_amount',
	Total_loan_amount: 'Total_loan_amount',
	Borrowmoney: 'Borrowmoney',
	Buildpartnerships: 'Buildpartnerships',
	AccountScreen: 'AccountScreen',
	NoticeScreen: 'NoticeScreen',
	LanguageScreen: 'LanguageScreen',
	EditAccount: 'EditAccount',
	Addcustomers: 'Addcustomers',
	AboutScreen: 'AboutScreen',
	PrivacyScreen: 'PrivacyScreen',
	CustomerInformation: 'CustomerInformation',
	Addinvestors: 'Addinvestors',
	Addinvestors2: 'Addinvestors2',
	Investors2: 'Investors2',
	Investors3: 'Investors3',
	InvestorInformation: 'InvestorInformation',
	Repaymentschedule: 'Repaymentschedule',
	PaymentScreen: 'PaymentScreen',
	Paywithcash: 'Paywithcash',
	PaywithKHQRCode : 'PaywithKHQRCode',
}